ifpe-cti/saudegaranhuns

README.md

#2 Incrementar a Documentação

---

.travis.yml

Corrigido bug do Travis que não permitia a compilação do código.

Atualização da configuração do Travis CI

---

src/main/webapp/AlterarAtendenteForm.xhtml
src/main/webapp/AtualizaPacienteForm.xhtml
src/main/webapp/AtualizaPostoSaude.xhtml
src/main/webapp/CadastroAtendenteForm.xhtml
src/main/webapp/CadastroPacienteForm.xhtml
src/main/webapp/CadastroPostoSaudeForm.xhtml
src/main/webapp/LoginAtendente.xhtml
src/main/webapp/LoginPaciente.xhtml
src/main/webapp/WEB-INF/web.xml

Paginas Web de Cadastro e Atualização de Paciente, Atendente e Posto
e Atualização de Cadastro de Paciente Conforme Issue 31

Conforme Issues 20 21 e 31

---

README.md

#61 Melhorias da documentação

---

src/main/java/br/edu/ifpe/garanhuns/sg/recursos/ApplicationConfig.java
src/main/java/br/edu/ifpe/garanhuns/sg/recursos/ConsultasResource.java

Criação do serviço para cadastrar pedido de consulta conforme issue #27

---

src/main/java/br/edu/ifpe/garanhuns/sg/controller/ConsultaController.java
src/main/webapp/consulta/cadastro.xhtml

Criar cadastro e atualização de consultas #24

---

src/main/java/br/edu/ifpe/garanhuns/sg/recursos/ConsultasResource.java
src/main/webapp/test-services.html

De acordo com a issue #28 , cria serviço de listagem de consulta por paciente.

#28 Criar o serviço de listagem de consultas

---

src/main/java/br/edu/ifpe/garanhuns/sg/recursos/ApplicationConfig.java
src/main/java/br/edu/ifpe/garanhuns/sg/recursos/PostosResource.java
src/main/webapp/test-services.html

De acordo com a issue #29 , adicionado serviço Rest para listagem dos Postos de Saúde.

#29 Criar service para retornar os postos de saúde

---

src/main/java/br/edu/ifpe/garanhuns/sg/controller/ConsultaController.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/AtendenteHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/AtendimentoHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/BairroHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/ConsultaHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/EnderecoHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/FilaAtendimentoHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/HorarioAtendimentoHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/PacienteHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/PostoSaudeHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/UsuarioHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/BairroDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/DAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/EnderecoDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/PacienteDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/PostoSaudeDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/UsuarioDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/recursos/ConsultasResource.java
src/main/java/br/edu/ifpe/garanhuns/sg/recursos/PacientesResource.java
src/main/java/br/edu/ifpe/garanhuns/sg/util/NewClass.java

Seguindo o que foi solicitado no issue 56 os nomes dos métodos foram alterado de inglês para português.

Mudando o nome das classe de Inglês para português

---

docs/uml/saudegaranhuns-classes.uml

#71 Atualização do diagrama de classes

---

README.md

#72 Atualizar documentação explicando como criar os diagramas

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/pojo/enumarador/DiasSemana.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/pojo/enumarador/Especialidade.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/pojo/enumarador/Prioridade.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/pojo/enumarador/Status.java

Alterar enumerações para melhor visualização na view

---

src/main/java/br/edu/ifpe/garanhuns/sg/converter/AtendenteConverter.java
src/main/java/br/edu/ifpe/garanhuns/sg/converter/ConsultaConverter.java
src/main/java/br/edu/ifpe/garanhuns/sg/converter/PacienteConverter.java
src/main/java/br/edu/ifpe/garanhuns/sg/converter/PostoSaudeConverter.java

Conforme a issue #65, implementando conversores para as classes que poderão ser usadas no SelectOneMenu

 #65 Criar converter das classes das entidades

---

README.md
pom.xml
src/main/java/br/edu/ifpe/garanhuns/sg/Aplicacao.java

#16 Adicionado suporte ao SpringBoot com Tomcat embedded

---

src/main/resources/hibernate.cfg.xml

Conforme issue #88 , alterando property do hibernate.cfg.

#88 Alterando property do hibernate.cfg conforme issue

---

src/main/java/br/edu/ifpe/garanhuns/sg/recursos/PacientesResource.java

#91 Corrigindo erro ao cadastrar paciente no BD conforme issue

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/ConsultaHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/enumarador/Prioridade.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/enumarador/Status.java

#96 Alterar e adicionar valores nas enumerações

---

src/main/webapp/consulta/cadastro.xhtml
src/main/webapp/consulta/listagem.xhtml

#95 Corrigir propriedade das enumerações na páginas de consulta

---

README.md

#90 Documentação do bug referente a espaços em branco do Spring Boot

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/BairroHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/EnderecoHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/PostoSaudeHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/EnderecoDAO.java

Conforme foi pedido por @jofernando da issue #125.

#125 Corrigir exceção lançada no PostoSaudeHibernate

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/Atendente.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/Atendimento.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/Bairro.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/Consulta.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/Endereco.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/FilaAtendimento.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/HorarioAtendimento.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/Paciente.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/PostoSaude.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/Usuario.java
src/main/java/br/edu/ifpe/garanhuns/sg/util/NewClass.java
src/main/resources/hibernate.cfg.xml

Como foi solicitado  foi adicionado o strategy nos Id's das classes pojos.

#94 adição do strategy

---

README.md

#108 Alterar a documentação para utilizar o maven-wrapper

---

src/main/java/br/edu/ifpe/garanhuns/sg/controller/AtendenteController.java
src/main/java/br/edu/ifpe/garanhuns/sg/controller/PacienteController.java
src/main/java/br/edu/ifpe/garanhuns/sg/controller/PostoSaudeController.java
src/main/webapp/atendente/alterar.xhtml
src/main/webapp/atendente/cadastro.xhtml
src/main/webapp/paciente/alterar.xhtml
src/main/webapp/paciente/cadastro.xhtml
src/main/webapp/posto/alterar.xhtml
src/main/webapp/posto/cadastro.xhtml

Alterações dos Controllers segundo issue #101

#101 Alteração dos controllers de todas as telas da inteface Web

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/ConsultaHibernate.java

correção de erro no método recuperarConsultasPorPaciente

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/Paciente.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/Usuario.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/PacienteHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/PacienteDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/enumarador/PerfilUsuario.java
src/main/java/br/edu/ifpe/garanhuns/sg/util/NewClass.java

Conforme issue #127 houve as alterações para que usuário tenha um perfil

Adicionado enum PerfilUsuario conforme as alterações das UML

---

src/main/java/br/edu/ifpe/garanhuns/sg/converter/LocalDateConverter.java

#136 Criar converter para LocalDate

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/Atendente.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/Atendimento.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/Bairro.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/Consulta.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/Endereco.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/FilaAtendimento.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/HorarioAtendimento.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/Paciente.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/PostoSaude.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/Usuario.java

#134 Implementar os métodos equals() e hashCode() nas classes de entidade

---

.gitignore
src/main/java/br/edu/ifpe/garanhuns/sg/recursos/PostosResource.java
src/test/java/br/edu/ifpe/garanhuns/sg/recursos/PostosResourceTest.java

Alteração nas anotações no serviço Rest de postos

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/Paciente.java
src/test/java/br/edu/ifpe/garanhuns/sg/model/PacienteTest.java

Adicionando função para validação do JSON de Paciente, conforme issue #142.

#142 Criação da validação JSON de Paciente

---

src/main/java/br/edu/ifpe/garanhuns/sg/controller/PostoSaudeController.java
src/main/resources/hibernate.cfg.xml
src/main/webapp/atendente/listagem.xhtml
src/main/webapp/consulta/listagem-do-dia.xhtml
src/main/webapp/paciente/listagem.xhtml
src/main/webapp/posto/alterar.xhtml
src/main/webapp/posto/listagem.xhtml

#84 Arquivos JSF com problemas de namespace ou de módulos

---

src/main/webapp/atendente/menu.xhtml
src/main/webapp/index.xhtml

#116 Criar o menu superior para o atendente

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/Consulta.java
src/test/java/br/edu/ifpe/garanhuns/sg/model/ConsultaTest.java

#152 Criar validação JSON de Consulta

---

src/main/java/br/edu/ifpe/garanhuns/sg/controller/PostoSaudeController.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/Consulta.java
src/main/java/br/edu/ifpe/garanhuns/sg/recursos/ConsultasResource.java
src/main/java/br/edu/ifpe/garanhuns/sg/recursos/PacientesResource.java
src/main/resources/hibernate.cfg.xml
src/main/webapp/atendente/listagem.xhtml
src/main/webapp/atendente/menu.xhtml
src/main/webapp/consulta/listagem-do-dia.xhtml
src/main/webapp/index.xhtml
src/main/webapp/paciente/listagem.xhtml
src/main/webapp/posto/alterar.xhtml
src/main/webapp/posto/listagem.xhtml
src/test/java/br/edu/ifpe/garanhuns/sg/model/ConsultaTest.java
src/test/java/br/edu/ifpe/garanhuns/sg/recursos/PacientesResourceTest.java

#120 Alterar anotações do serviço Rest de Consultas

---

src/main/java/br/edu/ifpe/garanhuns/sg/controller/AtendenteController.java
src/main/java/br/edu/ifpe/garanhuns/sg/controller/LoginUsuarioController.java
src/main/java/br/edu/ifpe/garanhuns/sg/controller/PacienteController.java
src/main/java/br/edu/ifpe/garanhuns/sg/controller/PacienteLoginController.java
src/main/java/br/edu/ifpe/garanhuns/sg/controller/PostoSaudeController.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/AtendenteHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/util/NewClass.java
src/main/resources/hibernate.cfg.xml
src/main/webapp/atendente/cadastro.xhtml
src/main/webapp/paciente/alterar.xhtml
src/main/webapp/paciente/cadastro.xhtml
src/main/webapp/posto/cadastro.xhtml

Segundo issue #101  termino de alterações nos controlerrs como complemento do PR #124 
terminados os cadastros de paciente, posto e atendente e criado relação com usuario

#101 termino de alterações nos controlerrs

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/Usuario.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/UsuarioHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/UsuarioDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/util/NewClass.java

Conforme a issue #139.
@Igor201

criado método recuperarUsuarioPorLogin(String login, String senha)

---

src/main/java/br/edu/ifpe/garanhuns/sg/recursos/PacientesResource.java

De acordo com a issue #155 , criação do serviço Rest para possibilitar Login no mobile.

#155 Criar serviço Rest para consultar paciente pelo cartão do SUS

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/Consulta.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/ConsultaHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/ConsultaDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/util/NewClass.java
src/main/resources/hibernate.cfg.xml

Conforme @jofernando solicitou.

#161 Criação do método recuperarConsultasDoDia(LocalDate dia);

---

src/main/webapp/paciente/menu.xhtml

#165 Criar o menu superior para o paciente

---

src/main/java/br/edu/ifpe/garanhuns/sg/controller/ConsultaController.java
src/main/webapp/consulta/listagem-do-dia.xhtml

#114 Implementar a ação para que o atendente indique o status do atendimento

---

src/main/webapp/visitante/menu.xhtml

#168 Criar o menu superior para o visitante

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/AtendimentoHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/ConsultaHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/HorarioAtendimentoHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/AtendenteDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/AtendimentoDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/BairroDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/ConsultaDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/DAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/EnderecoDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/FilaAtandimentoDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/HorarioAtendimentoDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/PacienteDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/PostoSaudeDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/UsuarioDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/util/NewClass.java
src/main/resources/hibernate.cfg.xml

Na criação do método método agendamentoAutomaticoConsulta() foi necessário a criação de outros métodos(abaixo listado) para auxilio. Como o esse algoritmo é de caráter urgente e não tinha um colaborador online no momento da criação, não foi adotado o procedimento correto na implementação do código no projeto(criar uma issue, codificar e submeter cara método no seu lugar). Espero a compreensão de todos!
//Em AtendimentoDAO 
public List<Atendimento> recuperarAtendimentoPorPostoEspecialidade(PostoSaude posto, Especialidade especialidade);
//em HorarioAtendimentoDAO
public List<HorarioAtendimento> recuperarHorarioAtendimentoPorPostoSaude(PostoSaude ps);
public List<HorarioAtendimento> recuperarHorarioAtendimentoPorPostoSaudeEspecialidade(PostoSaude ps, Especialidade especialidade);
//Em …

#35 Método de Agendamento Automatico

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/enumarador/DiasSemana.java

#174 Alteração do valores de DiasSemana.

---

src/main/java/br/edu/ifpe/garanhuns/sg/Aplicacao.java
src/main/java/br/edu/ifpe/garanhuns/sg/controller/LoginUsuarioController.java
src/main/java/br/edu/ifpe/garanhuns/sg/filter/AdminFilter.java
src/main/java/br/edu/ifpe/garanhuns/sg/filter/AtendenteFilter.java
src/main/java/br/edu/ifpe/garanhuns/sg/filter/PacienteFilter.java
src/main/java/br/edu/ifpe/garanhuns/sg/filter/VisitanteFilter.java
src/main/webapp/atendente/alterar.xhtml
src/main/webapp/atendente/cadastro.xhtml
src/main/webapp/atendente/listagem.xhtml
src/main/webapp/atendente/login.xhtml
src/main/webapp/atendente/menu.xhtml
src/main/webapp/consulta/cadastro.xhtml
src/main/webapp/consulta/listagem-do-dia.xhtml
src/main/webapp/consulta/listagem.xhtml
src/main/webapp/index.xhtml
src/main/webapp/menus.xhtml
src/main/webapp/paciente/alterar.xhtml
src/main/webapp/paciente/cadastro.xhtml
src/main/webapp/paciente/listagem.xhtml
src/main/webapp/paciente/login.xhtml
src/main/webapp/posto/alterar.xhtml
src/main/webapp/posto/cadastro.xhtml
src/main/webapp/posto/listagem.xhtml

#118 Gerenciar o direcionamento após o login dos usuários

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/AtendenteHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/UsuarioHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/interfaces/AtendenteDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/util/NewClass.java

Conforme a issue #180.
@jjunio01 está ai!

#180  implementação do método recuperarAtendentePorUsuario(Usuario usuario)

---

src/main/java/br/edu/ifpe/garanhuns/sg/recursos/AgendamentoResource.java

#163 Criar serviço Rest que recupera as datas disponíveis para agendamento

---

src/main/webapp/admin/menu.xhtml
src/main/webapp/atendente/login.xhtml
src/main/webapp/paciente/login.xhtml

Conforme a issue #117 foi criado o menu superior para o Administrador

#117 Criação do menu do admin

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/ConsultaHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/enumarador/Status.java
src/main/java/br/edu/ifpe/garanhuns/sg/util/NewClass.java

#146 Alteração de FILA para ATENDIMENTO no enum Status

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/ConsultaHibernate.java

conforme issue  #185 
@jofernando tinha uma aspa fora do lugar, mas esta executando, por favor verifique se é isso que vc gostaria!

#185 Correção de erros nos sout e mudando nomes das tabelas nas consultas

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/AtendenteDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/AtendimentoDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/BairroDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/ConsultaDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/DAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/EnderecoDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/FilaAtandimentoDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/HorarioAtendimentoDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/PacienteDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/PostoSaudeDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/UsuarioDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/AtendenteHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/AtendimentoHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/BairroHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/ConsultaHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/EnderecoHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/FilaAtendimentoHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/HorarioAtendimentoHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/PacienteHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/PostoSaudeHibernate.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/UsuarioHibernate.java

#192 Remoção do pacote interface e movendo os DAO's para o pacote DAO

---

src/test/java/br/edu/ifpe/garanhuns/sg/model/ConsultaTest.java
src/test/java/br/edu/ifpe/garanhuns/sg/model/PacienteTest.java

#200 Criar testes unitários para models de Paciente e Consulta.

---

src/main/webapp/visitante/menu.xhtml

#171 Modificar o menu de Login

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/PacienteDAO.java
src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/PacienteHibernate.java

Conforme issue #160.
@jofernando foi mau a demora.

# 160 Criação do método recuperarPacientePorUsuario(Usuario usuario)

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/HorarioAtendimentoHibernate.java

#206  Criação do método corricaoDiaSemana(List<HorarioAtendimento> listaAntiga)

---

src/main/webapp/admin/menu.xhtml
src/main/webapp/atendente/menu.xhtml

#195 Corrigir menu de admin e atendente

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/ConsultaHibernate.java

Alterado a linha 265 do ConsultaHibernate de if (consultas.size() <= horariosAtandimento.get(i).getQuantidade()) para if (consultas.size() < horariosAtandimento.get(i).getQuantidade())
conforme issue #212

#212 Alteração da linha 265 da ConsultaHibernate

---

src/main/webapp/atendente/cadastro.xhtml
src/main/webapp/atendente/login.xhtml
src/main/webapp/paciente/cadastro.xhtml
src/main/webapp/paciente/login.xhtml

#197 Gerenciamento das páginas após os cadastros

---

src/main/java/br/edu/ifpe/garanhuns/sg/model/dao/hibernate/HorarioAtendimentoHibernate.java
src/main/resources/hibernate.cfg.xml

conforme issue #214.
o erro está no teste.

#214 Remoção do correcaoDiaSemana

---

src/main/webapp/index.html

#211 A página principal não está abrindo automaticamente 

---

src/main/webapp/index.xhtml

#220 Adicionado Corpo do index.xhtml

---

src/main/webapp/horario-atendimento/cadastro.xhtml
src/main/webapp/paciente/menu.xhtml

#222 Adicionar menu na página de cadastro de horário de atendimento
